// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpqhxzcxqakyoavitcvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcWh4emN4cWFreW9hdml0Y3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzcxMDEsImV4cCI6MjA3MTcxMzEwMX0.B2ZQuk0qicjklEZ3m8DF4fQdiXriULFQMSMh-bf3foI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});